function [Pinflex, Ppv, Pev, Pflex] = values(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [PINFLEX, PPV, PEV, PFLEX] = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as column vectors.
%
%  [PINFLEX, PPV, PEV, PFLEX] = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  [PINFLEX, PPV, PEV, PFLEX] = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Pinflex, Ppv, Pev, Pflex] = importfile("C:\Users\Debjanee\Desktop\24hr problem\loadgen.xlsx", "Sheet1", [2, 25]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Nov-2022 20:52:09

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 25];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Pinflex", "Ppv", "Pev", "Pflex"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
Pinflex = tbl.Pinflex;
Ppv = tbl.Ppv;
Pev = tbl.Pev;
Pflex = tbl.Pflex;
end